<a href="https://colab.research.google.com/github/Hongbi-Kim/Writing_lyrics/blob/master/ANOVA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from scipy.stats import bartlett

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/writing_lyrics/assessment.csv')

In [5]:
df = df[['댄스_가사1(평가)', '댄스_가사2(평가)', '댄스_가사3(평가)', '발라드_가사1(평가)','발라드_가사2(평가)', '발라드_가사3(평가)']][:-2]
df

    댄스_가사1(평가)  댄스_가사2(평가)  댄스_가사3(평가)  발라드_가사1(평가)  발라드_가사2(평가)  발라드_가사3(평가)
0          5.0         1.0         1.0          5.0          1.0          5.0
1          4.0         5.0         4.0          4.0          4.0          5.0
2          2.0         1.0         1.0          1.0          4.0          5.0
3          4.0         4.0         3.0          4.0          1.0          1.0
4          3.0         4.0         4.0          5.0          4.0          5.0
5          4.0         2.0         2.0          2.0          2.0          4.0
6          2.0         4.0         4.0          3.0          4.0          4.0
7          5.0         5.0         5.0          5.0          5.0          5.0
8          4.0         1.0         2.0          4.0          2.0          4.0
9          4.0         5.0         1.0          2.0          3.0          2.0
10         4.0         4.0         3.0          4.0          2.0          4.0
11         2.0         5.0         4.0          4.0          4.0          5.0
12         1.0         5.0         5.0          4.0          4.0          4.0
13         2.0         1.0         5.0          2.0          1.0          5.0
14         5.0         3.0         4.0          5.0          3.0          2.0
15         2.0         4.0         2.0          4.0          2.0          2.0
16         3.0         4.0         1.0          3.0          3.0          3.0
17         2.0         4.0         2.0          3.0          2.0          4.0
18         1.0         4.0         1.0          5.0          4.0          4.0
19         2.0         4.0         4.0          5.0          3.0          2.0
20         3.0         2.0         1.0          2.0          3.0          4.0
21         5.0         1.0         5.0          3.0          3.0          5.0
22         5.0         3.0         2.0          4.0          2.0          2.0
23         2.0         5.0         3.0          5.0          3.0          1.0
24         4.0         4.0         2.0          2.0          3.0          4.0
25         1.0         1.0         5.0          1.0          1.0          2.0
26         4.0         5.0         2.0          5.0          5.0          1.0
27         2.0         2.0         5.0          5.0          2.0          4.0
28         1.0         2.0         4.0          4.0          2.0          2.0
29         4.0         4.0         4.0          4.0          4.0          4.0
30         2.0         4.0         4.0          2.0          2.0          4.0
31         4.0         2.0         1.0          2.0          4.0          1.0
32         1.0         5.0         5.0          5.0          4.0          5.0
33         5.0         1.0         2.0          5.0          3.0          2.0
34         4.0         2.0         2.0          2.0          4.0          4.0
35         5.0         5.0         5.0          4.0          3.0          4.0
36         4.0         3.0         5.0          4.0          2.0          3.0
37         5.0         2.0         2.0          5.0          1.0          1.0
38         5.0         2.0         5.0          5.0          1.0          4.0
39         4.0         5.0         5.0          5.0          5.0          5.0
40         3.0         4.0         4.0          4.0          2.0          4.0
41         3.0         4.0         3.0          3.0          3.0          2.0
42         5.0         1.0         1.0          1.0          5.0          5.0
43         3.0         5.0         5.0          5.0          5.0          5.0
44         5.0         5.0         5.0          5.0          5.0          5.0
45         5.0         5.0         5.0          5.0          5.0          5.0
46         1.0         5.0         2.0          4.0          2.0          2.0
47         4.0         5.0         3.0          2.0          1.0          4.0
48         5.0         1.0         1.0          1.0          5.0          5.0
49         3.0         4.0         3.0          3.0          3.0          4.0
50         3.0         5.0         2.0          2.0          2.0          2.0
51         5.0         2.0         4.0          4.0          1.0          4.0
52         1.0         3.0         4.0          4.0          2.0          2.0
53         2.0         5.0         2.0          2.0          5.0          5.0

- 댄스

In [ ]:
# H0: 등분산이다.
# Ha : 등분산이 아니다
bartlett(df['댄스_가사1(평가)'], df['댄스_가사2(평가)'], df['댄스_가사3(평가)'])

BartlettResult(statistic=0.2752445617342744, pvalue=0.8714277845366917)

In [ ]:
bartlett(df['발라드_가사1(평가)'], df['발라드_가사2(평가)'], df['발라드_가사3(평가)'])

BartlettResult(statistic=0.07651696375487024, pvalue=0.9624641292008487)

In [ ]:
import scipy.stats as stats

In [ ]:
# HO : 평균1 = 평균2 = 평균3
# HA : 귀무가설이 아니다.
f_statistic, p_val = stats.f_oneway(df['댄스_가사1(평가)'], df['댄스_가사2(평가)'], df['댄스_가사3(평가)'])
print('f_statistic : ', f_statistic)
print('p_val : ', p_val)
# ANOVA는 평균 차이 검정
# p-value가 유의하지 않다.(>0.5) 귀무가설 기각을 못하니까 -> 평균이 모두 같다. ->

f_statistic :  0.37438396670682256
p_val :  0.6883174111720841

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
f_statistic, p_val = stats.f_oneway(df['발라드_가사1(평가)'], df['발라드_가사2(평가)'], df['발라드_가사3(평가)'])
print('f_statistic : ', f_statistic)
print('p_val : ', p_val)

f_statistic :  3.3127147766323
p_val :  0.03894695255458479

In [10]:
# t - test
from scipy import stats
stats.ttest_ind(df['댄스_가사1(평가)'], (df['댄스_가사2(평가)']+df['댄스_가사3(평가)'])/2)
# 댄스 : 1 vs 2
# H0 : 평균1 = 평균2
# Ha : 평균1 != 평균2

Ttest_indResult(statistic=0.11187231421536643, pvalue=0.9111362207165425)

In [8]:
0.7405866716208667

0.7405866716208667

In [11]:
# 댄스 : 1 vs 3
stats.ttest_ind(df['발라드_가사1(평가)'], (df['발라드_가사3(평가)']+df['발라드_가사2(평가)'])/2)
# H0 : 평균1 = 평균3
# Ha : 평균1 != 평균3
# AI 평균평점과 실제가사의 평균평점의 "p-value 0.05하에서" 차이가 없다.
# -> 해석 : 인지능력

t-test -> 모집단(전체집단)에 대한 정보가 없음. -> 표본을 추출 -> 평균1 vs 평균 ->

Ttest_indResult(statistic=1.3332414575130667, pvalue=0.18531081391380055)